### PR TITLE
Build multiarch packages

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @jayfurmanek

**Comment by jakirkham** [comment]
The `aarch64` builds are failing as there is not a build of `flake8` for that platform. So have submitted PR ( https://github.com/conda-forge/flake8-feedstock/pull/36 ) to enable multiarch builds of `flake8`.

**Comment by jakirkham** [comment]
Have restarted the failing checks now that `aarch64` packages for `flake8` have been published and copied over to the CDN.

**Comment by jakirkham** [comment]
This is now passing! @mariusvniekerk, could you please take a look?

**Comment by jakirkham** [comment]
Friendly nudge 😉

**Comment by scottbelden** [comment]
If @mariusvniekerk doesn't get back I can merge it. I'm not really sure what's going on, but it's probably fine?

**Comment by jakirkham** [comment]
That would be great Scott! 😄

Basically this is just building packages on `ppc64le` and `aarch64` architectures. Appears there were no changes needed to the build (things just worked), which is great. So there's not too much to look at actually.

**Pull request merged**
