### PR TITLE
update to 0.16.6

### PR DESCRIPTION
**Pull request by scottbelden**

### CODE REVIEW

**Comment by scottbelden** [comment]
@mariusvniekerk Do you know why the travis tests seem to take forever to kick off? I made a [PR](https://github.com/conda-forge/fastavro-feedstock/pull/11) yesterday and those still haven't run. Today I tried making a PR with a native branch instead of a forked branch (to see if that had any impact) but I'm not sure that it changes anything.

Is this just the case of some huge backlog because conda-forge has many travis jobs running and they get queued up or is there something else going on?

Thanks!

**Comment by kmuehlbauer** [comment]
@scottbelden Travis backlog is over 24 hours atm. We can't do much about it, unfortunately.

**Comment by scottbelden** [comment]
@kmuehlbauer Gotcha. That's what I assumed but just wanted to make sure. Is there somewhere that I can see the backlog? If not, no worries. I'm sure it will get to these eventually.

**Comment by kmuehlbauer** [comment]
@scottbelden I gave up on finding the backlog list for conda-forge, when it exists somewhere it is well hidden. I usually look on Travis latest running conda-forge build and look when it was initiated...

**Comment by scottbelden** [comment]
Makes sense. Thanks again.

**Comment by mariusvniekerk** [comment]
Essentially since Travis dropped the number of concurrent jobs to 2 instead of 5 things have taken much longer.

**Comment by mariusvniekerk** [comment]
Also these won't work.  Please don't make branches on this repo for purposes of pull requests.  I'm going to have to close these to get the CI to work.  You have to do these from a fork.

**Comment by mariusvniekerk** [comment]
(otherwise all test builds try to get released and badness ensues)

**Pull request closed without merging**
